In this problem we build an algorithm to compute the inverse of a lower triangular matrix L.

We’ll use the tautology $L^{−1}L=I$, where $I$ is the identity matrix.

We know the elements of both L and I; the goal is to compute the elements of $L^{−1}$.
But first, what is the shape of the inverse matrix $L^{−1}$?  It turns out that if $L$ is lower triangular then $L^{−1}$ is also lower triangular.

This is a provable theorem, but for this problem you can just accept it as a fact.

Please do the following:

1. Knowing $L^{−1}L=I$, derive the equations which each element of $L^{−1}$ must obey.
This is a pencil and paper exercise.
I suggest you use write down the relation in terms of 3x3 matrices and create a table of equations for the elements of $L^{−1}$.
To help you I show a portion of my table.  (In my table I have named the elements of $L^{−1}$ as $q_{j,i}$)

$$L^{-1} = q = \begin{pmatrix} q_{1,1} & 0 & 0 \\ q_{2,1} & q_{2,2} & 0 \\ q_{3,1} & q_{3,2} & q_{3,3} \end{pmatrix}$$

$$L = \begin{pmatrix} L_{1,1} & 0 & 0 \\ L_{2,1} & L_{2,2} & 0 \\ L_{3,1} & L_{3,2} & L_{3,3} \end{pmatrix}$$

Apologize for this being a little messy, but:

$$L^{-1}L = \begin{pmatrix} q_{1,1}L_{1,1} & 0 & 0 \\ q_{2,1}L_{1,1} + q_{2,2}L_{2,1} & q_{2,2}L_{2,2} & 0 \\ q_{3,1}L_{1,1} + q_{3,2}L_{2,1} + q_{3,3}L_{3,1} & q_{3,2}L_{2,2} + q_{3,3}L_{3,2} & q_{3,3}L_{3,3} \end{pmatrix}$$

For any $i,j$

$$q_{i,i} = L_{i,i}^{-1}$$

$$q_{i,j} = \frac{-1}{L_{j,j}} \sum_{k=j}^{i}{q_{i, i-j}L_{1+k,j}}$$

In [28]:
import numpy as np

def inv(L):
    q = np.identity(1+L.shape[0]) - np.identity(1+L.shape[0])
    for i in range(1, L.shape[0]):
        for j in range(i, 0, -1):
            q[i][j] = (-1/L[j][j]) * sum(q[i][i-j]*L[1+k][j] for k in range(j, i))

    return q[1:,1:]

In [30]:
# Write a program which implements your algorithm and test it using lower triangular matrices of different sizes.

for i in range(20):
    # Create a bunch of random matrices A of different sizes
    shape = np.random.randint(3, 10)
    A = ((np.random.rand(shape, shape) + .1) * 10).astype(int) # Avoid zeros

    # Use Matlab’s lu() function to generate an upper triangular U from A to feed your program
    L = np.tril(A)
    # print(L)
    # arr = []
    # for a in np.identity(shape):
    #     arr.append(a)
    # arr = np.array(arr)
    # arr = np.rot90(arr)

    # To test I suggest you compute the residual r=‖L−1L−I‖ and verify it remains below a tolerance.
    res = np.linalg.norm(np.dot(inv(L), L) - np.identity(shape))

    # As testing tolerance I suggest you employ the matrix condition number to generate a tolerance for each new matrix by tol=eps(1)*cond(L)
    tol = np.finfo(float).eps*np.linalg.cond(L)

    if res > tol:
        print("DIDN'T WORK")
        print(inv(L))
        print(np.linalg.inv(L))
        print('\n')
    else:
        print("WORKED ±", res)
    # print("ACTUAL", np.linalg.inv(L), '\n\n', "MINE", arr)

DIDN'T WORK
[[-0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.]
 [-0. -0. -0.  0.  0.]
 [-0. -0. -0. -0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.66666667e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-1.42857143e-01  1.42857143e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-9.52380952e-02 -7.14285714e-02  5.00000000e-01 -1.04083409e-17
   7.70371978e-34]
 [ 1.85714286e-01 -8.57142857e-02 -4.00000000e-01  2.00000000e-01
  -1.54197642e-17]
 [-1.08843537e-02  4.89795918e-02 -5.71428571e-02 -2.57142857e-01
   1.42857143e-01]]


DIDN'T WORK
[[-0.  0.  0.  0.]
 [-0. -0.  0.  0.]
 [-0. -0. -0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.00000000e+00  1.58603289e-17 -4.06420929e-17  1.94289029e-17]
 [-1.50000000e+00  2.50000000e-01  7.28583860e-17 -2.91433544e-17]
 [-5.71428571e-01 -7.14285714e-02  1.42857143e-01 -1.11022302e-17]
 [ 1.90476190e+00  7.14285714e-02 -4.76190476e-01  3.33333333e-01]]


DIDN'T WORK
[[-0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.  0.]
 [-0. -0. 

## What is the time complexity of your algorithm?
$O(n^3)$

